# Generated by Django 5.1.3 on 2025-03-17 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_graph', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationship',
            name='entity2',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='entity1',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='source_article',
        ),
        migrations.DeleteModel(
            name='Entity',
        ),
        migrations.DeleteModel(
            name='Relationship',
        ),
    ]
