# Generated by Django 5.1.3 on 2025-03-23 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_relationship_relation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='source_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.newsarticle'),
        ),
    ]
