# Generated by Django 5.2.1 on 2025-05-15 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_newsarticle_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticle',
            name='keywords',
        ),
    ]
