# Generated by Django 5.1.3 on 2025-04-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_webpage_publication_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
    ]
