# Generated by Django 5.1.3 on 2025-03-17 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_graph', '0002_remove_relationship_entity2_and_more'),
        ('text_classification', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsArticle',
        ),
    ]
